language: go
sudo: false
addons:
  apt:
    packages:
    - libev-dev

go:
  - 1.5

install: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sLOf https://raw.githubusercontent.com/stampzilla/stampzilla-go/master/coverage
  - go get -d -t -v ./...

script: 
  - go test -v `go list ./... | grep -v telldus-events | grep -v stampzilla-hidcommander`
  - bash coverage  
  - goveralls -coverprofile=./gover.coverprofile -service travis-ci
