language: go
sudo: false

go:
- 1.11
install:
- go generate nodes/stampzilla-server/main.go
- go get -d -t -v ./...

script:
- make test
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go run build.go

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JBuaQNghrwATvyFiItYUeXMGIFr7Fy7SQwnM/kk1poMBoKTo2KduC7q+E5i+H7ZJCSOmO+IFLMEhnFDaAJ4tq4JWHC6lt56KXkkVz0XNyGSc69QoSWfv8vDBClYKpyhdNVTk3O73gK+h3R7etvFiMLccYJ4zGhJ6QxQVbFv5qoA=
  file_glob: true
  file: dist/*
  on:
    tags: true
    repo: stampzilla/stampzilla-go
    condition: $TRAVIS_GO_VERSION =~ ^1\.11

