language: go
sudo: false
addons:
  apt:
    packages:
    - libev-dev

go:
- 1.7
install:
- go get -d -t -v ./...

test:
  script:
  - make test
  - make cover-normal
  after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JBuaQNghrwATvyFiItYUeXMGIFr7Fy7SQwnM/kk1poMBoKTo2KduC7q+E5i+H7ZJCSOmO+IFLMEhnFDaAJ4tq4JWHC6lt56KXkkVz0XNyGSc69QoSWfv8vDBClYKpyhdNVTk3O73gK+h3R7etvFiMLccYJ4zGhJ6QxQVbFv5qoA=
  install:
  - go get github.com/laher/goxc
  script:
  - "./.xc-all.bash $TRAVIS_TAG"
  file: 
  - build/*/linux_amd64/*
  - build/*/linux_arm/*
  - build/*/*.deb
  on:
    tags: true
    repo: stampzilla/stampzilla-go
