language: go
sudo: false
addons:
  apt:
    packages:
    - libev-dev

go:
  - 1.7

install: 
  - go get -d -t -v ./...

script: 
  - make test
  - make cover-normal
after_success:
  - bash <(curl -s https://codecov.io/bash)
